### PR TITLE
require plone.app.registry >=1.5. Refs #42

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by erral** [comment]
@hvelarde can you check this?

I needed not only to require plone.app.registry >= 1.5 on setup.py but set also on the testing buildout because Plone 4.3.x's requirement is plone.app.registry = 1.2.5. To get that I had to split the testing buildout file into multiple ones and change the testing config on `.travis.yml`. Please if this configuration is or you'd rather do it in another way.

**Comment by hvelarde** [comment]
in fact is simpler than that; all you need to do is:

```yml
env:
  matrix:
    - PLONE_VERSION=4.3 VERSIONS=plone.app.registry=1.5
...
install:
...
- bin/buildout $VERSIONS annotate
- bin/buildout $VERSIONS
```

take a look at how this works on [collective.cover](https://github.com/collective/collective.cover/blob/master/.travis.yml).

**Comment by erral** [comment]
Thanks, it's in fact much easier...

**Comment by hvelarde** [comment]
thanks! I'm going to update lazysizes to 4.0.1 later and then make a new release:

https://github.com/aFarkas/lazysizes/releases/tag/4.0.1

**Pull request merged**
