### PR TITLE
Refactor resource registries test to run under Plone 5 also

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@ebrehault I'm trying your approach on checking static resources but for some unknown reason it's not working; resources appear to be in production mode instead of development, even as I declared explicitly that on the tests.

what I'm doing wrong?

**Comment by ebrehault** [comment]
@hvelarde I might be wrong, but I have the feeling you are using the `hvelarde-resources` branch so your bundle is not declared https://github.com/collective/collective.lazysizes/blob/hvelarde-resources/src/collective/lazysizes/profiles/default/registry.xml

It should work if you run this test on the `hvelarde-plone5` branch.

**Comment by hvelarde** [comment]
@ebrehault the point is the test is failing in Plone 4.3 also.

**Comment by ebrehault** [comment]
@hvelarde it took me some time, but I found a way to force the JS dev mode in the tests.
We have to add:
```self.portal.portal_javascripts.setDebugMode(True)```
in `setUp`.

At least, it fixes your test on Plone 4, I haven't tried on Plone 5 (I guess I have network issues, by the way I have also pushed the fix I just mentionned on your branch, but it seems like it is not properly retrieved on GitHub...)

**Comment by hvelarde** [comment]
@ebrehault that's pretty weird because I have [the exact same code](https://github.com/simplesconsultoria/collective.texttospeech/blob/master/src/collective/texttospeech/tests/test_resources.py) in another add-on and it's working there.

I think your change wont work in Plone 5.

**Comment by ebrehault** [comment]
We do have the same code in example.p4p5, and it works too. I spend a lot
of time trying to understand what is different in lazysizes, and I have
found anything.
If you find the explanation, please tell me :)

**Comment by hvelarde** [comment]
@vangheem can you point us in the right direction here? how do I verify if some JS or CSS resource is present in Plone 5; I'm trying development mode but my JS file is inside some RequireJS file.

how do I test that programatically?

**Comment by hvelarde** [comment]
I opened https://github.com/plone/Products.CMFPlone/issues/1511 for the later.

**Comment by hvelarde** [comment]
@ebrehault I think I can mark the package now as Plone 5 compatible; thank you!

**Pull request merged**
