### PR TITLE
revised explanation text

### PR DESCRIPTION
**Pull request by rileydog**

### CODE REVIEW

**Comment by gforcada** [comment]
@rileydog would you mind rebasing your changes? Unfortunately your merge request was not merged at that time and some other changes got in between.

**Comment by hvelarde** [comment]
also, I'm not full in favor of merging this; the grammar may be enhanced but I don't think it explains better what the package does.

we need more opinions.

**Comment by rileydog** [comment]
Hi,  @gforcada and @hvelarde    Not sure what action there is for me to do.  I'm sorry, but I'm a complete nubbie on this branching and stuff.  I worked on this during the sprint at Boston.  If you folks don't think the changes are good, I trust your judgment.  Can you just delete them?  (see I don't understand how this works).  If I can do something to help, please let me know.

**Comment by hvelarde** [comment]
don't worry; thanks anyway!

**Pull request closed without merging**
